---
name: eudi-lib-ios-siop-openid4vp-swift
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          echo "tests"

          fastlane tests # fastlane just_build