---
name: eudi-lib-ios-siop-openid4vp-swift
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          git config --add url."https://${{ secrets.USER_NAME }}:${{
          secrets.USER_GITHUB_TOKEN
          }}@github.com/niscy-eudiw/eudi-lib-ios-presentation-exchange-swift.git".insteadof
          https://github.com/niscy-eudiw/eudi-lib-ios-presentation-exchange-swift.git

          fastlane tests # fastlane just_build