---
name: eudi-lib-ios-siop-openid4vp-swift
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}
      - run:
          fastlane just_build